name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: install go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: linter
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.14.0
      - name: go vet
        run: go vet ./...
  test:
    name: Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd "pg_isready -U postgres -d db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: db
      POSTGRES_SSL: disable
    steps:
      # 1. checkout
      - name: Checkout code
        uses: actions/checkout@v5
      # 2. setup-go
      - name: install go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      # 3. поставить goose
      - name: install goose
        run: go install github.com/pressly/goose/v3/cmd/goose@v3.14.0

      # 4. прогнать миграции
      - name: Migrations
        run: goose -dir ./migrations postgres "host=$POSTGRES_HOST port=$POSTGRES_PORT user=$POSTGRES_USER password=$POSTGRES_PASSWORD dbname=$POSTGRES_DB sslmode=$POSTGRES_SSL" up -v
      # 5. go test ./... -race -cover
      - name: Tests
        run: go test ./... -race -cover
  docker:
    name: Docker build (${{ matrix.image }})
    needs: [lint, test]
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
    strategy:
      matrix:
        image: [server, migrations]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Hadolint для docker
        uses: hadolint/hadolint-action@v3.1.0
        with: 
          dockerfile: ./docker/${{ matrix.image }}.Dockerfile
      - name: SetUp Docker BuildX
        uses: docker/setup-buildx-action@v4
      - name: Login to GHCR
        if: github.event_name == 'push'
        uses: docker/login-action@v4
        with: 
          regestry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}-${{ matrix.image }}
          tags: |
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Build
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./docker/${{ matrix.image }}.Dockerfile
          push: ${{github.event_name == 'push'}}
          tags: ${{steps.meta.outputs.tags}}
          labels: ${{steps.meta.outputs.labels}}
          cache-from: type=gha,scope=${{matrix.image}}
          cache-to: type=gha,mode=max,scope=${{matrix.image}}
